/**
 * Worker bindings plus the variables that are not declared in wrangler.jsonc.
 *
 * `Env` itself is generated by `wrangler types` from the bindings in
 * wrangler.jsonc (ARTIFACTS, DB). The fields added here come from secrets or
 * from `.dev.vars`, so they are all optional at the type level and every
 * consumer has to handle their absence.
 */
export interface AppEnv extends Env {
  /**
   * Only ever set to "local" (via .dev.vars) or "test" (via vitest.config.ts).
   * It is deliberately absent from wrangler.jsonc, so a deployed Worker always
   * sees `undefined` here and can never take the development identity path.
   */
  readonly ENVIRONMENT?: string;
  /** Owner email used in place of Cloudflare Access during local development. */
  readonly DEV_OWNER_EMAIL?: string;
  /** e.g. "yourteam.cloudflareaccess.com". Set with `wrangler secret put`. */
  readonly ACCESS_TEAM_DOMAIN?: string;
  /** AUD tag of the Cloudflare Access application. Set with `wrangler secret put`. */
  readonly ACCESS_AUD?: string;
}

/** Environments in which the Cloudflare Access round trip is not available. */
const DEVELOPMENT_ENVIRONMENTS = new Set(["local", "test"]);

/**
 * True only when running under `wrangler dev` with .dev.vars, or under vitest.
 *
 * Because ENVIRONMENT is never written to wrangler.jsonc, this returns false in
 * every deployed environment regardless of how the Worker is invoked.
 */
export function isDevelopmentEnvironment(env: AppEnv): boolean {
  return env.ENVIRONMENT !== undefined && DEVELOPMENT_ENVIRONMENTS.has(env.ENVIRONMENT);
}
